### ISSUE TITLE
swat-2015-dataset,ipynb missing

### ISSUE THREAD

**Issue by aefferent** [cbhua/tool-swat-preprocess#2]
The swat-2015-dataset.ipynb is empty.

**Comment by cbhua** [comment]
Sorry for this late reply, it's got updated. Also you can refer to `/src/swatset.py` to check the script version.

**Comment by cbhua** [comment]
Dear Solomon Hatcher,&nbsp;

Sorry for this late reply and thanks for your remanding, there was an upload error that made this problem.&nbsp;

I will fix it these days.&nbsp;

Have a nice day!

Best,&nbsp;
Chuanbo.&nbsp;

-----Original Message-----
From: "Solomon Hatcher" ***@***.***&gt;
To: "cbhua/tool-swat-preprocess" ***@***.***&gt;;
Cc: "Subscribed" ***@***.***&gt;;
Sent: 2022-06-22 (We) 21:44:10 (UTC+09:00)
Subject: [cbhua/tool-swat-preprocess] swat-2015-dataset,ipynb missing (Issue #2)


The swat-2015-dataset.ipynb is empty.
